package core;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.times;

public class SavingsGoalManagerTest extends RequesterFactoryTest {
    SavingsGoalManager goalManager;
    String savingsGoalNonAutoCreatedResponse = """
            {"savingsGoalList":[{"savingsGoalUid":"176c7fea-ebe6-4cbc-8ce6-19ffa13684c0","name":"Not an auto created saving goal","target":{"currency":"GBP","minorUnits":123456},"totalSaved":{"currency":"GBP","minorUnits":0},"savedPercentage":0}]}
            """;
    String savingsGoalAutoGeneratedResponse = """
            {"savingsGoalList":[{"savingsGoalUid":"176c7fea-ebe6-4cbc-8ce6-19ffa13684c0","name":"Auto Savings Goal","target":{"currency":"GBP","minorUnits":123456},"totalSaved":{"currency":"GBP","minorUnits":0},"savedPercentage":0}]}
            """;

    String savingsGoalListEmpty = """
            {"savingsGoalList":[]}
            """;

    @Test
    public void testWhenAutoGeneratedSavingsGoalExists_thenReturnCorrectUid() throws Exception {
        goalManager = new SavingsGoalManager(factory, "12345");
        String expectedUid = "176c7fea-ebe6-4cbc-8ce6-19ffa13684c0";
        Mockito.when(factory.getRequestCommand(Mockito.any())).thenReturn(requester);
        Mockito.when(requester.getResponseBody()).thenReturn(savingsGoalAutoGeneratedResponse);
        String savingsGoalUid = goalManager.getOrCreateSavingsGoal();
        assertEquals(expectedUid, savingsGoalUid, "Expected: " + expectedUid + ", but was: " + savingsGoalUid);
    }

    @Test
    public void testWhenNotAutoGeneratedSavingsGoalExists_thenReturnCorrectUid() throws Exception {
        goalManager = new SavingsGoalManager(factory, "12345");
        Mockito.when(factory.getRequestCommand(Mockito.any())).thenReturn(requester);
        Mockito.when(requester.getResponseBody()).thenReturn(savingsGoalNonAutoCreatedResponse);
        String savingsGoalUid = goalManager.getOrCreateSavingsGoal();
        assertEquals("", savingsGoalUid, "Expected: <empty>, but was: " + savingsGoalUid);
    }

    @Test
    public void testWhenFirstRequestIsEmptySecondReturnsUid_thenUidIsSet() throws Exception {
        goalManager = new SavingsGoalManager(factory, "12345");
        String expectedUid = "176c7fea-ebe6-4cbc-8ce6-19ffa13684c0";
        Mockito.when(factory.getRequestCommand(Mockito.any())).thenReturn(requester);
        Mockito.when(requester.getResponseBody()).thenReturn(savingsGoalListEmpty).thenReturn(savingsGoalAutoGeneratedResponse);
        String savingsGoalUid = goalManager.getOrCreateSavingsGoal();
        assertEquals(expectedUid, savingsGoalUid, "Expected: " + expectedUid + ", but was: " + savingsGoalUid);
    }
}
